### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by justandras** [musicorum-app/web#66]
Add a way for users to create a calendar feed that they can link up with their calendar app, where they could see their events from Last.fm

**Comment by MysteryMS** [comment]
Could you give us a detailed example of you how would use this feature?

**Comment by justandras** [comment]
You would be able to request an ICS / iCal Feed URL in musicorum that would contain your events you responded "Going" or "Interested" on lastfm.

You would be able to take this URL and put it in Outlook or Google calendar, so you could share this calendar from there with others or your friends so they see your events in their calendar too.

Since it doesn't change often, updates/requests could be limited to 1x per day, to reserve server resources

**Comment by MysteryMS** [comment]
I don't think there's a way to see the events a user marked as interested or going in directly from the last.fm api

**Comment by MysteryMS** [comment]
gimme some time to understand this correctly

**Comment by MysteryMS** [comment]
yeah, that's what i have thought. there's no currently known way to fetch events you marked as interested or going in
